name: youtube-drive-downloader

on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:

  run:

    runs-on: ubuntu-latest

    env:
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt update
        sudo apt install ffmpeg nodejs -y

    - name: create token
      run: echo '${{ secrets.TOKEN_JSON }}' > token.json

    - name: run script
      run: python downloader.py

    - name: commit changes
      run: |
        git config --global user.name "bot"
        git config --global user.email "bot@github.com"
        git add pending.txt completed.txt failed.txt
        git commit -m "update queue" || echo "no change"
        git push
