name: youtube-drive-downloader

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:

  run:

    runs-on: ubuntu-latest

    env:
      DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: install dependencies
      run: |
        pip install yt-dlp pydrive2
        sudo apt update
        sudo apt install ffmpeg -y

    - name: create token
      run: echo '${{ secrets.TOKEN_JSON }}' > token.json

    - name: run script
      run: python downloader.py
